services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: battleships-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: battleships-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api


networks:
  default:
    name: recipe-network
    driver: bridge